//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSRService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public string Cluster { get; set; }
        public string Hash { get; set; }
        public string fHash { get; set; }
        public string Stack { get; set; }
        public string FirstFile { get; set; }
        public string Trainer { get; set; }
    }
}
